language: node_js
node_js:
- 14
script: DBUSERNAME=CS3219Admin DBPASSWORD=cs3219admin npm run test
dist: trusty
deploy:
  provider: lambda
  region: ap-southeast-1
  access_key_id:
    secure: NJ9u+njaDUSE7RWNSqQpZDFv+cE0wkmZfml/a8LzKtFeusLPS2AjWh5tAHlz9cWv1ob8mvDA13fa0W6/VH4kHE/YOsehJuZS6zT6D3u4fcV4m+KCzL/IVPQGxTZ0jgGdOLFR/Lh7HbS/mKlnADuOmlR/QskjIKSjcdQtn4OHomU0rkSbaGrcjcUf+pK7NZA09aP/t8hH39IQSbwxrjOqXTqCZpPdZKY7lnoaPO8vOgGZaao6hoKO19Zpg5IjSrbw/YIxZ95UkABzB85kwQhiSS5UFL8tlcy0pFHJDlEeUifFDxNottRI3PG26ucqUpfBXFVbnDh/6ZNfExwJflbw+KvZY3Xr1/vY+2zAITwlrLuAcfwPPBIKozHkgGKZutgNVwtyfQCeGyG6wwUmC7YPY7cNIqbYzklchFDk9GPEFOFPFvL9WBaUqgwBbrNNop/uTHUBKeCoRTiHq3ZlOHqDLheRrsBqWJgKR03Vs4rsIZPFu26HU0PolB1PJsBC7FOLYGatjR8JMaxCQOPd5glvZgr32Av5S2gvzDVS5XVEk9+ayhAWC7ygqgfWAeW9fIJ5fFbjzxmWilv+V9NAwhW6PbnfaR6Sv94fuJLibRGR1Gdkddfxn0vhwWGyxwjjOu6AnrzrBzVNPGz3ADe/BVvhecnaVf3r66TYV9ogbPnlIDE=
  secret_access_key:
    secure: ghS1zCklfSeih9nyz3C8dCF2TOKOy34xMERdlRusjSwbLlJDMOXsAaKDBFhWVqA8Ac/goTrZwykGCaoc9xBmTQS0Ddpz8bWs4KETyRjZB7B7vYjc3NX1Z8KwuJD3rSLtKauhJkVdhUaiXOrcDU4FhkhI1w17t6IMTSWm0FKMfBjJs461wp9fAVi35Jng6G0XiG2SmhMhgcv4+V9rCwyuu+NF2Sf32fuwLgEwoIBuW/IDGnemR96eH0I6sl99He3s6UyVFHDGkI0FwFI4Y4c2sgzbt49o9aO/l9calMLpCFirAP+evmNQL0HdndLYhCiCWk3p1IeXIPycANU+HRW6RFp613QfNGMu8yO6gpvFSEtvTXP7NESMkzNKdYFxwz9iTP4wQlODLSFQyFQ+pRz1C1fy7QFpY00HnAWabEx5her7yhMGbJWc/Z/HZ5GLZQARUAg9ZQqf6BPNOrY3Ak2O/LNGieFXhQbFM+Ykq5bJRkZ6W454XPQ3OH86C/NQv8pRgMSbwviucDhjpzzr7hw+qOexfb7ia1tkipXhPIBsbtMiG31zkbgbCfGd/GuvTnN3xhzRu1Qwb9VLGi2pfDFce6wF7PpBHkncasndbfW6tP7eh3YZJ0R982glwp/Cin4A7+hI2/97pUsdPWrD5pACNra5hYz+8LQTkBlUYAJzp/g=
  function_name: taskb-deploy
  role: "arn:aws:iam::425563513848:role/travis"
  handler_name: "lambda.handler"
  edge: true